export const logo = require('./logo.svg')
export const landing = require('./landing.svg')
export const study = require('./icons/study.svg')
export const giveClasses = require('./icons/give-classes.svg')
export const purpleHeart = require('./icons/purple-heart.svg')
export const back = require('./icons/back.svg')
export const whatsapp = require('./icons/whatsapp.svg')